In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np.arange(100, 200, 10).reshape(5, 2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [3]:
sampleArray = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[:][2]

array([77, 88, 99])

In [4]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [5]:
sum_array = arrayOne + arrayTwo

In [6]:
sum_array

array([[20, 39, 33],
       [25, 25, 28]])

In [7]:
np.multiply(sum_array, sum_array)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

Pandas

In [8]:
df = pd.read_csv("C:/Users/Maryam Yusuf/Downloads/Automobile_data.csv")

In [9]:
df.head()

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [10]:
df.tail()

index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   index             61 non-null     int64  
 1   company           61 non-null     object 
 2   body-style        61 non-null     object 
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object 
 6   num-of-cylinders  61 non-null     object 
 7   horsepower        61 non-null     int64  
 8   average-mileage   61 non-null     int64  
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB


In [12]:
df.replace(["?", "n.a"], value = "NaN", inplace = True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   index             61 non-null     int64  
 1   company           61 non-null     object 
 2   body-style        61 non-null     object 
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object 
 6   num-of-cylinders  61 non-null     object 
 7   horsepower        61 non-null     int64  
 8   average-mileage   61 non-null     int64  
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB


In [14]:
df.isnull().sum()

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [15]:
x= df["price"].max()
x

45400.0

In [16]:
df["price"].idxmax()

35

In [17]:
df.iloc[35]

index                          47
company             mercedes-benz
body-style                hardtop
wheel-base                    112
length                      199.2
engine-type                  ohcv
num-of-cylinders            eight
horsepower                    184
average-mileage                14
price                       45400
Name: 35, dtype: object

In [18]:
df["company"].groupby(df["company"]).count()

company
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2
honda            3
isuzu            3
jaguar           3
mazda            5
mercedes-benz    4
mitsubishi       4
nissan           5
porsche          3
toyota           7
volkswagen       4
volvo            2
Name: company, dtype: int64

In [19]:
df["price"].groupby(df["company"]).max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [20]:
df["average-mileage"].groupby(df["company"]).mean()

company
alfa-romero      20.333333
audi             20.000000
bmw              19.000000
chevrolet        41.000000
dodge            31.000000
honda            26.333333
isuzu            33.333333
jaguar           14.333333
mazda            28.000000
mercedes-benz    18.000000
mitsubishi       29.500000
nissan           31.400000
porsche          17.000000
toyota           28.714286
volkswagen       31.750000
volvo            23.000000
Name: average-mileage, dtype: float64

In [21]:
df.sort_values(by=["price"])

index        company body-style  wheel-base  length engine-type  \
13     16      chevrolet  hatchback        88.4   141.1           l   
27     36          mazda  hatchback        93.1   159.1         ohc   
48     66         toyota  hatchback        95.7   158.7         ohc   
36     49     mitsubishi  hatchback        93.7   157.3         ohc   
28     37          mazda  hatchback        93.1   159.1         ohc   
..    ...            ...        ...         ...     ...         ...   
11     14            bmw      sedan       103.5   193.8         ohc   
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
22     31          isuzu      sedan        94.5   155.9         ohc   
23     32          isuzu      sedan        94.5   155.9         ohc   
47     63        porsche  hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
13            three          48               47   5151.0  
27             four          68               30   5195.0  
48             four          62               35   5348.0  
36             four          68               37   5389.0  
28             four          68               31   6095.0  
..              ...         ...              ...      ...  
11              six         182               16  41315.0  
35            eight         184               14  45400.0  
22             four          70               38      NaN  
23             four          70               38      NaN  
47            eight         288               17      NaN  

[61 rows x 10 columns]

In [22]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
GermCar_data = pd.DataFrame(GermanCars)
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
japaCar_data = pd.DataFrame(japaneseCars)

In [23]:
japaCar_data.head()

Company  Price
0       Toyota  29995
1        Honda  23600
2       Nissan  61500
3  Mitsubishi   58900

In [24]:
GermCar_data.head()

Company   Price
0      Ford   23845
1  Mercedes  171995
2       BMV  135925
3      Audi   71400

In [25]:
conc_data = pd.concat([japaCar_data, GermCar_data], keys=["japaneseCars", "GermanCars"])

In [26]:
conc_data

Company   Price
japaneseCars 0       Toyota   29995
             1        Honda   23600
             2       Nissan   61500
             3  Mitsubishi    58900
GermanCars   0         Ford   23845
             1     Mercedes  171995
             2          BMV  135925
             3         Audi   71400

In [27]:
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [28]:
Car_Price = pd.DataFrame(Car_Price)
Car_Price

Company   Price
0  Toyota   23845
1   Honda   17995
2     BMV  135925
3    Audi   71400

In [29]:
car_Horsepower = pd.DataFrame(car_Horsepower)
car_Horsepower

Company  horsepower
0  Toyota         141
1   Honda          80
2     BMV         182
3    Audi         160

In [30]:
pd.merge(Car_Price, car_Horsepower, on="Company", how = "right")

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

In [31]:
url ="https://docs.google.com/spreadsheets/d/1gjcf7DSibeiDHMnYnW0vqTx5zA4S29UJ/edit#gid=2000719128"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
sales_df = pd.read_csv(url)

ParserError: Error tokenizing data. C error: Expected 9 fields in line 7, saw 475
